import { Section } from "../components/ui/Section";
import { useLanguage } from "../context/LanguageContext";

const SECTIONS = [
  {
    title: "1. Who this policy covers",
    body: "This Privacy Policy describes how ComplAI, Inc. (\"ComplAI\", \"we\", \"us\") collects, uses, and shares personal information when you visit complai.example, use our platform, or otherwise interact with us. It applies to prospective customers, customers, and website visitors; it does not govern personal data our customers process using the ComplAI platform on their own behalf, which is instead governed by our Data Processing Agreement with that customer.",
  },
  {
    title: "2. Information we collect",
    body: "We collect information you provide directly (name, work email, company, and message content submitted through our contact form or newsletter signup), information collected automatically (IP address, browser type, pages visited, referring URL, via standard server logs), and information generated by your use of the AI assistant (the text of messages you send it, retained to improve response quality and for abuse prevention).",
  },
  {
    title: "3. How we use information",
    body: "We use this information to respond to inquiries and demo requests, operate and improve the website and assistant, send the newsletter to subscribers who opted in, detect and prevent abuse, and comply with legal obligations. We do not sell personal information, and we do not use contact-form or newsletter data to train third-party AI models.",
  },
  {
    title: "4. Legal basis for processing (EEA/UK visitors)",
    body: "Where the General Data Protection Regulation applies, we process your information based on: your consent (newsletter signups), our legitimate interests (responding to inquiries, securing the site), and performance of a contract where you have engaged us as a customer.",
  },
  {
    title: "5. Sharing of information",
    body: "We share information with service providers who process it on our behalf under contract (hosting, database, and analytics providers), and where required by law, subpoena, or to protect the rights and safety of ComplAI or others. We do not share contact-form submissions with advertisers.",
  },
  {
    title: "6. Data retention",
    body: "Contact form submissions are retained for 24 months from the date of submission, or until you request deletion, whichever is earlier. Newsletter subscriptions are retained until you unsubscribe. Assistant conversation logs are retained for 12 months for quality and abuse-prevention purposes, then deleted.",
  },
  {
    title: "7. Your rights",
    body: "Depending on your location, you may have the right to access, correct, delete, or export your personal information, and to object to or restrict certain processing. To exercise these rights, contact privacy@complai.example. We will respond within 30 days.",
  },
  {
    title: "8. Security",
    body: "We apply the same continuous-monitoring discipline to our own environment that we sell to customers: encryption in transit and at rest, least-privilege access controls, and continuous control monitoring against our internal SOC 2 program.",
  },
  {
    title: "9. International transfers",
    body: "Where personal information is transferred outside the region it was collected in, we rely on appropriate safeguards, including Standard Contractual Clauses where applicable.",
  },
  {
    title: "10. Changes to this policy",
    body: "We will post any material changes to this page with an updated effective date, and, where required by law, provide additional notice.",
  },
  {
    title: "11. Contact us",
    body: "Questions about this policy can be sent to privacy@complai.example or by mail to 548 Market Street, Suite 88000, San Francisco, CA 94104.",
  },
];

export default function Privacy() {
  const { t, language } = useLanguage();
  return (
    <div>
      <Section className="pb-8 max-w-3xl mx-auto">
        <p className="eyebrow mb-4">{t("footer.legal")}</p>
        <h1 className="font-display text-3xl md:text-4xl font-semibold tracking-tight">Privacy Policy</h1>
        <p className="text-sm text-[var(--color-text-muted)] mt-3">{t("legal.effective")}</p>
        {language === "ar" && (
          <p className="text-xs text-[var(--color-text-faint)] mt-4 italic">
            نص السياسة القانونية الكامل أدناه معروض بالإنجليزية حالياً، تجنباً لمخاطر الترجمة الآلية للنصوص القانونية.
          </p>
        )}
      </Section>
      <Section className="pt-0 max-w-3xl mx-auto space-y-8" dir="ltr">
        {SECTIONS.map((s) => (
          <div key={s.title}>
            <h2 className="font-display font-semibold mb-2">{s.title}</h2>
            <p className="text-sm text-[var(--color-text-muted)] leading-relaxed">{s.body}</p>
          </div>
        ))}
      </Section>
    </div>
  );
}
